### PR TITLE
Added ReplaceHeaders and ReplaceRules functionality

### PR DESCRIPTION
**Pull request by megamih**
Hi Vladimir,
Thank you for your module - it saved me time :) Hope, my pull request can be useful.
I use ReplaceHeaders and ReplaceRules to sign messages which will be masqueraded by sendmail, i.e. when the following exists in "/etc/mail/sendmail.mc"

```
MASQUERADE_AS(`example.com')dnl
MASQUERADE_DOMAIN(`example.com example.org example.net')dnl
FEATURE(`masquerade_envelope')dnl
FEATURE(`masquerade_entire_domain')dnl
```

For CentOS 6 opendkim RPM should be re-built to enable this functionality

```
diff -u ./opendkim-2.10.3/opendkim/opendkim-config.h.bak ./opendkim-2.10.3/opendkim/opendkim-config.h
--- opendkim-config.h.bak       2016-04-19 10:58:33.746001946 +0100
+++ opendkim-config.h   2016-04-19 11:02:20.024353330 +0100
@@ -144,6 +144,7 @@
        { "RemoveARFrom",               CONFIG_TYPE_STRING,     FALSE },
        { "RemoveOldSignatures",        CONFIG_TYPE_BOOLEAN,    FALSE },
 #ifdef _FFR_REPLACE_RULES
+       { "ReplaceHeaders",             CONFIG_TYPE_STRING,     FALSE },
        { "ReplaceRules",               CONFIG_TYPE_STRING,     FALSE },
 #endif /* _FFR_REPLACE_RULES */
        { "ReportAddress",              CONFIG_TYPE_STRING,     FALSE },

diff -u ./opendkim.spec.bak /opendkim.spec
--- opendkim.spec       2015-12-26 01:17:22.000000000 +0000
+++ ./rpmbuild/SPECS/opendkim.spec      2016-04-18 10:48:51.504291368 +0100
@@ -83,7 +83,7 @@
 %configure --with-odbx --with-db --with-libmemcached --with-openldap
 %else
 # Configure with options available to SysV
-%configure --with-odbx --with-db --with-openldap
+%configure --with-odbx --with-db --with-openldap --enable-replace_rules
 %endif

 # Remove rpath
```

### CODE REVIEW

**Comment by bi4o4ek** [comment]
Could you explain in more detail what this feature does?

**Comment by megamih** [comment]
Hi Vladimir,

My usecase: I have testlab with multiple servers, which use single mail relay as smart host to send outbound emails only (i.e. I do not serve inbound emails) - reporting, monitoring messages etc.
I control "example.com" domain only. But servers in test lab have different FROM domains - i.e. in FROM field can be something like noreply@example.com, noreply@test.example.org, noreply@example.dev etc.

I masquerade emails with MASQUERADE_AS(`example.com') in sendmail - this causes mail being sent to be labeled as coming from the indicated example.com, rather than from test.example.org, example.dev etc.

For sendmail flow looks like this:
1. sendmail sees email "from=noreply@test.example.org"
2. sendmail passes it to opendkim for signing
3. opendkim signs "from=noreply@test.example.org" header
4. sendmail does masquerading, i.e. changes "from=noreply@test.example.org" to "from=noreply@example.com"
5. DKIM signature is broken :(

I have two options to not break DKIM signature:
1. Have 2 sendmails:
- sendmail01 does masquearading and has sendmail02 as smart_host
- sendmail02 + opendkim signs and relays messages
1. Use opendkim's ReplaceHeaders and ReplaceRules functionality (which I chose :)

With second option (which is configured with pullreqeust) flow looks like:
1. sendmail sees email "from=noreply@test.example.org"
2. sendmail passes it to opendkim for signing
3. opendkim changes "from=noreply@test.example.org" to "from=noreply@example.com" according to ReplaceHeaders and ReplaceRules
4. opendkim signs "from=noreply@example.com" header
5. sendmail does masquerading, i.e. changes "from=noreply@test.example.org" to "from=noreply@example.com"
6. DKIM signature is fine :)

Best regards,
Oleksandr

**Comment by megamih** [comment]
Hi Vladimir,

If you mean checksums section in "metadata.json" - did it in [6380bcc](https://github.com/bi4o4ek/puppet-opendkim/pull/8/commits/6380bcc51a874b8971fc6cf2ce9c5c5f6fbb72c6).

Best regards,
Oleksandr

**Comment by bi4o4ek** [comment]
Thank you!

**Pull request merged**
